CREATE TABLE IF NOT EXISTS TableSeating(
TableNum INT(6) NOT NULL
,OccupiedStatus BOOLEAN NOT NULL
,PRIMARY KEY (TableNum)
);

CREATE TABLE IF NOT EXISTS Reservation(
ReservationID INT(6) AUTO_INCREMENT NOT NULL
,ResDate DATE NOT NULL
,ResTime VARCHAR(5) NOT NULL
,PRIMARY KEY (ReservationID)
);

CREATE TABLE IF NOT EXISTS ReservationTableSeating(
ReservationID INT(6) NOT NULL
,TableNum INT(6) NOT NULL
,PRIMARY KEY (ReservationID, TableNum)
,FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID)
,FOREIGN KEY (TableNum) REFERENCES TableSeating(TableNum)
);


CREATE TABLE IF NOT EXISTS OrderLogs(
OrderID INT(6) AUTO_INCREMENT NOT NULL
,OrdDate DATE NOT NULL
,OrdTime VARCHAR(5) NOT NULL
,PricePayed FLOAT(10) NOT NULL
,PRIMARY KEY (OrderID)
);

CREATE TABLE IF NOT EXISTS MenuItem(
MenuItemID INT(6) AUTO_INCREMENT NOT NULL
,Name VARCHAR(20) NOT NULL
,Description VARCHAR(20) NOT NULL
,Price FLOAT(10) NOT NULL
,NutritionInfo VARCHAR(20) NOT NULL
,MenuStatus boolean
,PRIMARY KEY (MenuItemID)
);

CREATE TABLE IF NOT EXISTS OrderMenuItem(
OrderID INT(6) NOT NULL
,MenuItemID INT(6) NOT NULL
,Quantity int(6) NOT NULL
,ItemPrice FLOAT(10) NOT NULL
,PRIMARY KEY (OrderID, MenuItemID)
,FOREIGN KEY (OrderID) REFERENCES OrderLogs(OrderID)
,FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID)
);

CREATE TABLE IF NOT EXISTS OrderMenuItem(
OrderID INT(6) NOT NULL
,MenuItemID INT(6) NOT NULL
,Quantity int(6) NOT NULL
,ItemPrice FLOAT(10) NOT NULL
,PRIMARY KEY (OrderID, MenuItemID)
,FOREIGN KEY (OrderID) REFERENCES OrderLogs(OrderID)
,FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID)
);

CREATE TABLE IF NOT EXISTS Day(
DayID INT(6) NOT NULL
,DayName  VARCHAR(20) NOT NULL
,PRIMARY KEY (DayID)
);

CREATE TABLE IF NOT EXISTS DaySales(
MenuItemID INT(6) NOT NULL
,DayID INT(6) NOT NULL
,Amount INT(6) NOT NULL
,PRIMARY KEY (MenuItemID, DayID)
,FOREIGN KEY (MenuItemID ) REFERENCES MenuItem(MenuItemID)
,FOREIGN KEY (DayID) REFERENCES Day(DayID)
);

CREATE TABLE IF NOT EXISTS TimeFrame(
TimeFrameID INT(6) NOT NULL
,timeFrame VARCHAR(20)  NOT NULL
,PRIMARY KEY (TimeFrameID)
);

CREATE TABLE IF NOT EXISTS SaleTimes(
MenuItemID INT(6) NOT NULL
,TimeFrameID INT(6) NOT NULL
,Amount INT(6) NOT NULL
,PRIMARY KEY (MenuItemID, TimeFrameID)
,FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID)
,FOREIGN KEY (TimeFrameID) REFERENCES TimeFrame(TimeFrameID)
);

CREATE TABLE IF NOT EXISTS Account(
Username VARCHAR(30) NOT NULL
,PassWord VARCHAR(30) NOT NULL
,PRIMARY KEY (UserName)
);