CREATE TABLE IF NOT EXISTS Reservation(
ReservationID INT(6) AUTO_INCREMENT NOT NULL,
ResDate DATE NOT NULL,
ResTime VARCHAR(5) NOT NULL,
attendees INTEGER NOT NULL,
PRIMARY KEY (ReservationID)
);

CREATE TABLE IF NOT EXISTS OrderLogs(
OrderID INT(6) AUTO_INCREMENT NOT NULL
,OrdDate DATE NOT NULL
,OrdTime VARCHAR(5) NOT NULL
,PRIMARY KEY (OrderID)
);

CREATE TABLE IF NOT EXISTS MenuItem(
MenuItemID INT(6) AUTO_INCREMENT NOT NULL
,Name VARCHAR(20) NOT NULL
,Description VARCHAR(20) NOT NULL
,Price FLOAT(10) NOT NULL
,NutritionInfo VARCHAR(20) NOT NULL
,MenuStatus boolean
,PRIMARY KEY (MenuItemID)
);

CREATE TABLE IF NOT EXISTS OrderMenuItem(
OrderID INT(6) NOT NULL
,MenuItemID INT(6) NOT NULL
,Quantity int(6) NOT NULL
,PRIMARY KEY (OrderID, MenuItemID)
,FOREIGN KEY (OrderID) REFERENCES OrderLogs(OrderID)
,FOREIGN KEY (MenuItemID) REFERENCES MenuItem(MenuItemID)
);

CREATE TABLE IF NOT EXISTS Day(
DayID INT(6) NOT NULL
,DayName  VARCHAR(20) NOT NULL
,PRIMARY KEY (DayID)
);

INSERT INTO Day (DayID, DayName) VALUES (1, 'Monday');
INSERT INTO day (DayID, DayName) VALUES (2, 'Tuesday');
INSERT INTO day (DayID, DayName) VALUES (3, 'Wednesday');
INSERT INTO day (DayID, DayName) VALUES (4, 'Thursday');
INSERT INTO day (DayID, DayName) VALUES (5, 'Friday');
INSERT INTO day (DayID, DayName) VALUES (6, 'Saturday');
INSERT INTO day (DayID, DayName) VALUES (7, 'Sunday');

CREATE TABLE IF NOT EXISTS DaySales(
MenuItemID INT(6) NOT NULL
,DayID INT(6) NOT NULL
,Amount INT(6) NOT NULL
,PRIMARY KEY (MenuItemID, DayID)
,FOREIGN KEY (MenuItemID ) REFERENCES MenuItem(MenuItemID)
,FOREIGN KEY (DayID) REFERENCES Day(DayID)
);

/* THE FOLLOWING ALTERS ARE ONLY NEEDED IF YOU HAVE TAKEN THE TABLES FROM A PREVIOUS VERSION. IF THIS IS THE FIRST TIME YOU HAVE ACQUIRED THE TABLES, FEEL FREE TO IGNORE

ALTER TABLE reservation ADD COLUMN attendees INTEGER NOT NULL AFTER resTime;
ALTER TABLE `orderlogs` DROP COLUMN `pricepayed`;
ALTER TABLE `ordermenuitem` DROP COLUMN `ItemPrice`;
*/