POST http://localhost:5000/api/order/create
content-type: application/json

{
    "customerName": "Tim Sandra",
    "totalCost": "15",
    "table": "4",
    "orderType": "inRestaurant",
    "menuItems": [
        {
            "name": "Steak",
            "quantity": 1,
            "Description": "Porterhouse Stake",
            "id": 1,
            "menuStatus": 1
        },
        {
            "id": 2,
            "quantity": 2
        }
    ]
}